# Generated by Django 3.2.16 on 2023-01-12 18:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Question',
            fields=[
                ('sl_no', models.AutoField(primary_key=True, serialize=False)),
                ('quest', models.TextField(max_length=500)),
                ('op_1', models.CharField(default=None, max_length=50)),
                ('op_2', models.CharField(default=None, max_length=50)),
                ('op_3', models.CharField(default=None, max_length=50)),
                ('op_4', models.CharField(default=None, max_length=50)),
                ('ans', models.CharField(max_length=50)),
                ('desc', models.TextField(default=None, max_length=500)),
                ('timeStamp', models.DateTimeField(blank=True)),
            ],
        ),
    ]
