# Generated by Django 3.2.16 on 2023-01-12 18:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Point', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('slnum', models.AutoField(primary_key=True, serialize=False)),
                ('cat', models.CharField(max_length=50)),
            ],
        ),
    ]
