# Generated by Django 3.2.16 on 2023-01-12 19:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Point', '0004_auto_20230113_0024'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Question',
        ),
    ]
