# Generated by Django 3.2.16 on 2023-01-12 19:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Point', '0007_question_cat'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='cat',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='Point.category'),
        ),
    ]
