# Generated by Django 3.2.16 on 2023-01-12 19:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Point', '0008_alter_question_cat'),
    ]

    operations = [
        migrations.RenameField(
            model_name='question',
            old_name='cat',
            new_name='category',
        ),
    ]
