# Generated by Django 3.2.16 on 2023-01-13 17:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Point', '0010_category_parent'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='cat_img',
            field=models.ImageField(blank=True, upload_to='static/category_media'),
        ),
    ]
