# Generated by Django 3.2.16 on 2023-01-16 19:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Point', '0013_result'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name_plural': 'Categories'},
        ),
    ]
