# Generated by Django 3.2.16 on 2023-01-16 19:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Point', '0017_result'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='name',
            field=models.CharField(default='No Name', max_length=100),
        ),
        migrations.AddField(
            model_name='category',
            name='number_of_questions',
            field=models.IntegerField(default=10),
        ),
        migrations.AddField(
            model_name='category',
            name='required_score',
            field=models.IntegerField(default=60, help_text='required score to pass the quiz.'),
        ),
        migrations.AddField(
            model_name='category',
            name='time',
            field=models.IntegerField(default=1, help_text='duration of the quiz in minutes.'),
        ),
    ]
